CREATE POLICY "beaos_brand_isolation" ON "brand_opportunities" AS PERMISSIVE FOR ALL TO public USING ("brand_opportunities"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("brand_opportunities"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "citations" AS PERMISSIVE FOR ALL TO public USING ("citations"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("citations"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "competitors" AS PERMISSIVE FOR ALL TO public USING ("competitors"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("competitors"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "prompt_run_attempts" AS PERMISSIVE FOR ALL TO public USING ("prompt_run_attempts"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("prompt_run_attempts"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "prompt_runs" AS PERMISSIVE FOR ALL TO public USING ("prompt_runs"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("prompt_runs"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "prompts" AS PERMISSIVE FOR ALL TO public USING ("prompts"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("prompts"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "provider_calls" AS PERMISSIVE FOR ALL TO public USING ("provider_calls"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("provider_calls"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "agent_aos_audits" AS PERMISSIVE FOR ALL TO public USING ("agent_aos_audits"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("agent_aos_audits"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "agent_aps_prompt_libraries" AS PERMISSIVE FOR ALL TO public USING ("agent_aps_prompt_libraries"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("agent_aps_prompt_libraries"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "agent_aps_runs" AS PERMISSIVE FOR ALL TO public USING ("agent_aps_runs"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("agent_aps_runs"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "agent_assets" AS PERMISSIVE FOR ALL TO public USING ("agent_assets"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("agent_assets"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "agent_brand_claims" AS PERMISSIVE FOR ALL TO public USING ("agent_brand_claims"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("agent_brand_claims"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "agent_brand_dna_snapshots" AS PERMISSIVE FOR ALL TO public USING ("agent_brand_dna_snapshots"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("agent_brand_dna_snapshots"."brand_id" = current_setting('beaos.brand_id', true));--> statement-breakpoint
CREATE POLICY "beaos_brand_isolation" ON "agent_brand_entities" AS PERMISSIVE FOR ALL TO public USING ("agent_brand_entities"."brand_id" = current_setting('beaos.brand_id', true)) WITH CHECK ("agent_brand_entities"."brand_id" = current_setting('beaos.brand_id', true));